# Generated by Django 5.0.7 on 2024-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_attribute_attributevalue_category_comment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
