# Generated by Django 5.0.7 on 2024-07-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_auth_group_auth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auths', to='book.category')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
