# Generated by Django 5.0.7 on 2024-07-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_group_table_auth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
